### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by rabol** [alt-design/Alt-Starter-Kit#1]
Hi 

Thanks for the starterkit!

Question: in the layout.antlers.html, body tag, there is a dynamic css class 
```
<body class="alt_starter_kit page-{{ slug }} relative" x-data="{navOpen: false, modalOpen: false}">
```
What is the thought behind it as TW normally don't like that

**Comment by Alt-Ben** [comment]
Hey @rabol! 

Thanks for trying out/using the starter kit - always good to see people using the stuff we make!

The dynamic class there is for page-specific styling, it's not really related to TW in any way, it's just so that if you wanted to, for example, only style a particular row on the contact page, if you really wanted to you, you could do something like:

```body.page-contact .form-row form { background: pink; }```

If that makes sense? Basically a fallback option for non-Tailwind related stuff. Absolutely fine to remove if you like!
